Feature/queue to db
JoniDG/file-uploader pull request #1
Opened 2023-03-28 01:26 UTC by JoniDG

2023-03-28 01:50 UTC, luxarts requested changes
Excelente, me encantó lo del `InitRedis` y el `InitPostgres` (aunque en Go no se suelen usar la palabra `Init` en esos casos sino `New`).
Buen laburo, papá!

2023-03-28 01:50 UTC, luxarts commented on .gitignore
> +example2.csv
Metelo en una carpeta `files` y pone el gitignore a toda la carpeta como `files/`

2023-03-28 01:50 UTC, luxarts commented on internal/controller/upload.go
> +	UploadFile([]string)
```suggestion
	UploadFile(fileName string)
```

2023-03-28 01:50 UTC, luxarts commented on internal/controller/upload.go
> +func (c *uploadController) UploadFile(fileName []string) {
Que reciba el nombre del archivo directamente

2023-03-28 01:50 UTC, luxarts commented on internal/defines/envs.go
> +	EnvPostgresHost     = "POSTGRES_HOST"
Esta env puede tener el `host:port`, por lo que la `POSTGRES_PORT` no se usaría.

2023-03-28 01:50 UTC, luxarts commented on internal/job/job.go
> +	postgresURI := fmt.Sprintf("postgres://%s:%s@%s:%s/postgres?sslmode=disable",
Cuando saques la variable de entorno del port, acordate de cambiar esto.

2023-03-28 01:50 UTC, luxarts commented on cmd/main.go
> +	j.Job()
No tiene mucho sentido el nombre `Job()` para la función. Se entendería mejor si fuera `Run()` o `Start()`, de esa manera sabrías que esta función es la que efectivamente inicia el job.

2023-03-28 01:50 UTC, luxarts commented on internal/job/job.go
> +		fileName, err := rc.BLPop(ctx, 0, defines.QueueUploadFile).Result()
BLPop devuelve una array de dos dimensiones. En la posición `0` guarda el nombre de la lista de la que sacó el elemento y en la posición `1` guarda el valor del elemento. Obviamente queres el valor por lo que vos te traes el `result`, y si es `!= nil && len(result) == 2` entonces solo agarrás el `result[1]`.

2023-03-28 01:50 UTC, luxarts commented on internal/repository/upload.go
> +	sqlBuilder tableSQL
```suggestion
	sqlBuilder *tableSQL
```

2023-03-28 01:50 UTC, luxarts commented on internal/repository/upload.go
> +		sqlBuilder: tableSQL{
```suggestion
		sqlBuilder: &tableSQL{
```

2023-03-28 01:50 UTC, luxarts commented on internal/repository/upload.go
> +	UploadFile(file *domain.File)
El nombre no debería ser `Create`?

2023-03-28 01:50 UTC, luxarts commented on internal/repository/upload.go
> +type UploadRepository interface {
El nombre no debería ser algo como `UsersRepository`?

2023-03-28 01:50 UTC, luxarts commented on internal/service/upload.go
> +		persona := domain.File{
Esto sería un `domain.User`

2023-03-28 01:50 UTC, luxarts commented on internal/service/upload.go
> +		id, err := strconv.Atoi(row[0])
Acá a modo sugerencia te diría que hagas una función mapper para agarrar toda una fila del CSV y mappearla al struct. De esa manera no te queda la lógica del mapeo acá suelta.

2023-03-28 01:58 UTC, JoniDG commented on internal/repository/upload.go
> +type UploadRepository interface {
No se si el archivo que me van a subir va a ser de usuarios o de lo que sea. El archivo csv que yo poseo de ejemplo es de users

2023-03-28 17:10 UTC, JoniDG commented on internal/service/upload.go
> +		persona := domain.File{
Corregido en cc7204551ef1b3c5ca66f0010dab30d824e72e9f pero con otro nombre.

2023-03-28 17:10 UTC, JoniDG commented on internal/repository/upload.go
> +		sqlBuilder: tableSQL{
Corregido en cc7204551ef1b3c5ca66f0010dab30d824e72e9f

2023-03-28 17:10 UTC, JoniDG commented on internal/defines/envs.go
> +	EnvPostgresHost     = "POSTGRES_HOST"
Corregido en cc7204551ef1b3c5ca66f0010dab30d824e72e9f

2023-03-28 17:11 UTC, JoniDG commented on internal/controller/upload.go
> +func (c *uploadController) UploadFile(fileName []string) {
Corregido en cc7204551ef1b3c5ca66f0010dab30d824e72e9f

2023-03-28 17:11 UTC, JoniDG commented on .gitignore
> +example2.csv
Corregido en cc7204551ef1b3c5ca66f0010dab30d824e72e9f

2023-03-28 17:31 UTC, luxarts requested changes

2023-03-28 17:31 UTC, luxarts commented on internal/defines/tables.go
> +	TableUploadFile = "upload.example"
La tabla debería ser algo como `users`. El schema podría ser algo como `core` o `main`.

2023-03-28 17:31 UTC, luxarts commented on internal/job/job.go
> +type Jobs interface {
```suggestion
type Job interface {
```

2023-03-28 17:31 UTC, luxarts commented on internal/job/job.go
> +func NewJob() Jobs {
```suggestion
func NewJob() Job {
```

2023-03-28 17:31 UTC, luxarts commented on internal/job/job.go
> +			log.Println(err)
Acá te conviene poner un `continue` después del `Println` para que vuelva al inicio del `for` en vez de seguir el flujo.

2023-03-28 17:31 UTC, luxarts commented on internal/repository/upload.go
> +type UploadRepository interface {
Correcto pero como estas haciendo el ejemplo con users, deberías hacer el repository de users así queda el ejemplo completo. Cuando nos manden distintos formatos de archivos vamos a tener que hacer los service y repository que correspondan a cada uno.

2023-03-30 20:01 UTC, merged

2023-03-31 23:18 UTC, JoniDG commented on cmd/main.go
> +	err := godotenv.Load("./files/.env")
cambiar para autoload de carpeta base