Added error handling and go routine for controller
JoniDG/file-uploader pull request #2
Opened 2023-03-31 23:22 UTC by JoniDG

2023-03-31 23:41 UTC, luxarts requested changes
Bien negro, ahora hay que hacer tests 👍

2023-03-31 23:41 UTC, luxarts commented on internal/job/job.go
> +			go ctrl.UploadFile(&result[1])
Esto podríamos hacer que el controller devuelva un error y hacer un wrapping de esto en una función anónima.
```suggestion
			go func(){
			   err := ctrl.UploadFile(&result[1])
			   if err != nil {
			     log.Println(err)
			   }
			}()
```

2023-03-31 23:41 UTC, luxarts commented on internal/service/user.go
> +			Msg:      "Error al leer el archivo",
Traducir a inglés.

2023-03-31 23:41 UTC, luxarts commented on internal/service/user.go
> +			e := domain.Error{
Falta puntero
```suggestion
			e := &domain.Error{
```

2023-03-31 23:41 UTC, luxarts commented on internal/service/user.go
> +func ReadFile(file *os.File) ([][]string, error) {
Esto estaría bueno que devuelva un puntero asi evitamos que se duplique en memoria
```suggestion
func ReadFile(file *os.File) (*[][]string, error) {
```

2023-03-31 23:41 UTC, luxarts commented on internal/service/user.go
> +	return rows, nil
Devolver puntero
```suggestion
	return &rows, nil
```

2023-03-31 23:41 UTC, luxarts commented on internal/service/user.go
> +			e := domain.Error{
Falta puntero
```suggestion
			e := &domain.Error{
```

2023-03-31 23:41 UTC, luxarts commented on internal/service/user.go
> +				Msg:      fmt.Sprintf("Error ID format: %+v\n", row),
Cambiar este mensaje por uno que sea mas descriptivo de dónde se produjo la falla y no de cómo.

2023-04-03 19:44 UTC, JoniDG commented on internal/job/job.go
> +			go ctrl.UploadFile(&result[1])
Corregido en b8e8f7b

2023-04-03 19:44 UTC, JoniDG commented on internal/service/user.go
> +				Msg:      fmt.Sprintf("Error ID format: %+v\n", row),
Corregido en b8e8f7b

2023-04-03 19:44 UTC, JoniDG commented on internal/service/user.go
> +			e := domain.Error{
Corregido en b8e8f7b

2023-04-03 19:44 UTC, JoniDG commented on internal/service/user.go
> +	return rows, nil
Corregido en b8e8f7b

2023-04-03 19:44 UTC, JoniDG commented on internal/service/user.go
> +func ReadFile(file *os.File) ([][]string, error) {
Corregido en b8e8f7b

2023-04-03 19:44 UTC, JoniDG commented on internal/service/user.go
> +			e := domain.Error{
Corregido en b8e8f7b

2023-04-03 19:44 UTC, JoniDG commented on internal/service/user.go
> +			Msg:      "Error al leer el archivo",
Corregido en b8e8f7b

2023-04-04 23:06 UTC, merged